[tools]
cmake = "latest"
python = "3.14"

[env]
_.python.venv = { path = "venv", create = true }
PYTHONPATH = "{{config_root}}/build"

[tasks]
requirements = "pip install -r requirements.txt"
build_test = "cmake -S . -B build -DPython3_EXECUTABLE=$(which python) && cmake --build build && python src/main.py"
build_macos = "cmake -S . -B build && cmake --build build && python3 src/main.py"
build_windows = "cmake -S . -B build && cmake --build build --config Debug && python src/main.py"

