[tools]
cmake = "latest"
python = "3.14"

[env]
_.python.venv = { path = "venv", create = true }

[tasks]
requirements = "pip install -r requirements.txt"
build_macos = { run = "cmake -S . -B build && cmake --build build && python3 src/main.py", env = { PYTHONPATH = "{{config_root}}/build" } }
build_windows = { run = "cmake -S . -B build && cmake --build build --config Debug && python src/main.py", env = { PYTHONPATH = "{{config_root}}/build/Debug" } }
